import path from "node:path";
import { findSecrets } from "@/shared/redact";

export const EXCLUDED_DIRS = new Set([
  ".git", "node_modules", ".next", "dist", "build", "out", "coverage", ".turbo", ".venv", "venv",
  "__pycache__", ".idea", ".vscode", "target", "vendor", ".cache", ".pytest_cache",
]);

const SECRET_FILE_NAMES = [
  /^\.env(\..*)?$/i, /^\.npmrc$/i, /^\.netrc$/i, /^\.pypirc$/i, /^id_(rsa|dsa|ecdsa|ed25519)(\.pub)?$/i,
  /^credentials(\..*)?$/i, /^secrets?(\..*)?$/i, /\.(pem|key|p12|pfx|jks|keystore|crt|cer)$/i, /^\.htpasswd$/i,
];
/** Templates that are meant to be committed and contain no real values. */
const SECRET_FILE_ALLOW = [/^\.env\.(example|sample|template)$/i];

const BINARY_EXTENSIONS = new Set([
  ".png", ".jpg", ".jpeg", ".gif", ".webp", ".ico", ".bmp", ".pdf", ".zip", ".gz", ".tar", ".tgz", ".7z",
  ".woff", ".woff2", ".ttf", ".otf", ".eot", ".mp3", ".mp4", ".mov", ".wasm", ".exe", ".dll", ".so", ".dylib",
  ".class", ".jar", ".bin", ".sqlite", ".db", ".pyc", ".psd", ".svgz",
]);

const GENERATED_NAME = [/\.min\.(js|css)$/i, /\.map$/i, /\.generated\.[a-z]+$/i, /\.snap$/i, /(^|\/)package-lock\.json$/i, /(^|\/)yarn\.lock$/i, /(^|\/)pnpm-lock\.yaml$/i, /\.lock$/i, /\.d\.ts$/i];
const GENERATED_HEADER = /@generated|DO NOT EDIT|auto-?generated|code generated by/i;

const LANGUAGES: Record<string, string> = {
  ".ts": "TypeScript", ".tsx": "TypeScript", ".js": "JavaScript", ".jsx": "JavaScript", ".mjs": "JavaScript", ".cjs": "JavaScript",
  ".py": "Python", ".go": "Go", ".rs": "Rust", ".java": "Java", ".kt": "Kotlin", ".rb": "Ruby", ".php": "PHP", ".cs": "C#",
  ".md": "Markdown", ".mdx": "Markdown", ".json": "JSON", ".yaml": "YAML", ".yml": "YAML", ".toml": "TOML", ".sql": "SQL",
  ".sh": "Shell", ".css": "CSS", ".html": "HTML", ".txt": "Text",
};

export function languageOf(filePath: string): string {
  return LANGUAGES[path.extname(filePath).toLowerCase()] ?? "Other";
}

export function isCodeLanguage(language: string): boolean {
  return ["TypeScript", "JavaScript", "Python", "Go", "Rust", "Java", "Kotlin", "Ruby", "PHP", "C#", "SQL", "Shell"].includes(language);
}

/** Cheap name-based checks that run before a file is opened. Returns a reason or null. */
export function excludeByName(relPath: string): string | null {
  const base = path.posix.basename(relPath);
  if (SECRET_FILE_ALLOW.some((r) => r.test(base))) return null;
  if (SECRET_FILE_NAMES.some((r) => r.test(base))) return "secret-file";
  if (BINARY_EXTENSIONS.has(path.extname(base).toLowerCase())) return "binary";
  if (GENERATED_NAME.some((r) => r.test(relPath))) return "generated";
  return null;
}

/** Checks that need file contents. Returns a reason or null. Never returns the content itself. */
export function excludeByContent(buf: Buffer, text: string): string | null {
  const head = buf.subarray(0, 8000);
  if (head.includes(0)) return "binary";
  if (GENERATED_HEADER.test(text.split("\n", 5).join("\n"))) return "generated";
  const lines = text.split("\n");
  if (lines.length > 0 && text.length / lines.length > 400 && lines.length < 50) return "minified";
  if (findSecrets(text).length > 0) return "secret-like-content";
  return null;
}

/** Files that describe the project to humans or agents. Their text is still untrusted data. */
export function isInstructionFile(relPath: string): boolean {
  const base = path.posix.basename(relPath).toLowerCase();
  return ["readme.md", "claude.md", "agents.md", "contributing.md", "agent_notes.md"].includes(base) || relPath.toLowerCase().startsWith("docs/");
}

export function isTestFile(relPath: string): boolean {
  return /(^|\/)(tests?|__tests__|spec)\//i.test(relPath) || /\.(test|spec)\.[a-z]+$/i.test(relPath) || /(^|\/)test_[^/]+\.py$/.test(relPath);
}

export function isManifest(relPath: string): boolean {
  return ["package.json", "pyproject.toml", "requirements.txt", "go.mod", "cargo.toml", "pom.xml", "build.gradle", "gemfile", "tsconfig.json"].includes(
    path.posix.basename(relPath).toLowerCase(),
  );
}

export function isEntryPoint(relPath: string): boolean {
  return /(^|\/)(index|main|app|server|cli)\.(ts|tsx|js|mjs|py|go|rs)$/i.test(relPath) || /(^|\/)(routes?|api)\.(ts|js|py)$/i.test(relPath);
}

const INJECTION_PATTERNS: { name: string; regex: RegExp }[] = [
  { name: "ignore-previous-instructions", regex: /\b(ignore|disregard|forget)\b[^.\n]{0,40}\b(previous|prior|above|earlier|all)\b[^.\n]{0,30}\binstructions?\b/i },
  { name: "system-override", regex: /\bsystem\s+(override|prompt|message)\b/i },
  { name: "role-tag", regex: /<\/?\s*(system|assistant|developer)\s*>/i },
  { name: "tells-assistant-what-to-do", regex: /\b(you|assistant)\s+(must|should|will)\s+(not\s+)?(ask|state|print|reveal|mark|approve|ignore)\b/i },
  { name: "requests-secret-disclosure", regex: /\b(print|reveal|output|leak|send)\b[^.\n]{0,40}\b(\.env|api[_ -]?key|secret|password|credentials?)\b/i },
  { name: "requests-approval", regex: /\bmark\b[^.\n]{0,30}\b(brief|ticket|spec|it)\b[^.\n]{0,20}\bapproved\b/i },
  { name: "addresses-ai-agents", regex: /\b(notes?|message|instructions?)\s+for\s+(ai|llm|coding)\s+(coding\s+)?(assistants?|agents?|models?)\b/i },
];

/** Heuristic prompt-injection detector. Flags are shown to the user; they never gate behavior. */
export function detectInjection(text: string): string[] {
  return INJECTION_PATTERNS.filter((p) => p.regex.test(text)).map((p) => p.name);
}
